version: '3.3'

services:
  gotidus:
    build: ./
    depends_on:
      - 'gotiduspgdb'

  gotiduspgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'ci'
      POSTGRES_INITDB_ARGS: '--auth-host=md5'
